name: source_maps
version: 0.10.11-dev
description: Library to programmatically manipulate source map files.
repository: https://github.com/dart-lang/source_maps

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  source_span: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  term_glyph: ^1.2.0
