name: source_maps
version: 0.10.12
description: A library to programmatically manipulate source map files.
repository: https://github.com/dart-lang/source_maps

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  source_span: ^1.8.0

dev_dependencies:
  dart_flutter_team_lints: ^0.1.0
  term_glyph: ^1.2.0
  test: ^1.16.0
