name: source_maps
version: 0.10.10-nullsafety.2

description: Library to programmatically manipulate source map files.
homepage: https://github.com/dart-lang/source_maps

environment:
  # This must remain a tight constraint until nnbd is stable
  sdk: '>=2.10.0-0 <2.12.0'

dependencies:
  source_span: '>=1.8.0-nullsafety <1.8.0'

dev_dependencies:
  test: ^1.16.0-nullsafety
  term_glyph: ^1.2.0-nullsafety
